module.exports = [
    {
      id: 'c43a324d-fe94-47cd-a6b7-428feca264dd',
      plant_id: '0738a646-6aa8-4d5e-b5bd-3c2f6c9a4d56',
      name: 'Cherokee Purple',
      description: 'The Cherokee Purple Heirloom Tomato is a purple coloured variety, cultivated by a Native American Cherokee tribe. The plants are highly productive, producing loads of 12 ounce beefsteak tomatoes with deep red interiors. Its complex sweet flavours make it one of the best tasting heirlooms.',
      sun: 'full',
      frost_tolerance: 'none',
      maturity_in_days: 80,
      footprint: 12,
      support: true,
      usda_zone: {value : [5, 6, 7, 8]}
    },
    {
      id: '0fd46f1a-175a-4b21-9ecb-17c3220c70a4',
      plant_id: 'ab152a53-8a17-45e2-a864-e9b985c66683',
      name: 'Sugar Daddy',
      description: 'A very productive, bushy plant that benefits from some support, Sugar Daddy snap pea seeds produce pods that become uniquely stringless, 8cm (3") snap peas. They grow in pairs near the top of the plant for easy picking. This variety has good disease resistance, but not to the enation virus that sometimes spreads in mid-summer.',
      sun: 'full',
      frost_tolerance: 'mild',
      maturity_in_days: 68,
      footprint: 2,
      support: true,
      usda_zone: {value :[3, 4, 5, 6, 7, 8, 9, 10, 11]}
    },
    {
      id: '3ab5037a-d1cb-44bd-95e7-bd425c98a981',
      plant_id: '0bdceca3-fafe-47de-8ac3-f57cfe3bbff9',
      name: 'Bolero',
      description: 'A great variety for home or market. Very sweet and crunchy, it is a good keeper in storage or in the ground. Roots are bright orange, up to 20cm (8") long, and slightly tapered, with the typical blunt Nantes tip. High level of resistance to Alternaria blights and powdery mildew.',
      sun: 'full',
      frost_tolerance: 'mild',
      maturity_in_days: 75,
      footprint: 1,
      support: false,
      usda_zone: {value : [2, 3, 4, 5, 6, 7, 8, 9, 10]}
    },
    {
      id: '57864375-b4ae-49af-936d-02be4070fde3',
      plant_id: '1b85555f-aff0-4c1f-8b15-31c17392a546',
      name: 'California Wonder',
      description: 'Few bell pepper varieties can compete with the reliable plants produced by California Wonder pepper seeds. In a greenhouse, open field, or in your backyard vegetable garden, this is the variety to grow if you love big, blocky sweet peppers that mature from green to bright fire engine red. The four-lobed fruits are heavy with perfectly smooth skins, and grow to nearly 13cm (5") long and 10cm (4") wide on plants that can grow to 65cm (28") tall.',
      sun: 'full',
      frost_tolerance: 'none',
      maturity_in_days: 75,
      footprint: 12,
      support: false,
      usda_zone: {value : [9, 10, 11]}
    },
    {
      id: 'edb0ab8c-b923-49bf-9aff-bc66b55427ba',
      plant_id: 'a4c96db8-35a6-4ff2-8a2d-79dd1977c563',
      name: 'Arapaho',
      description: 'This early-ripening hybrid has all the heat of regular cayenne chiles, but the fruits mature much earlier on stout, 45cm (18") tall plants. The fruits can be as long as 20cm (8"). Great for containers, Arapaho Pepper Seeds are productive and spicy, with a sweet red bell pepper undertone in its flavour. 30,000 - 50,000 SHU',
      sun: 'full',
      frost_tolerance: 'none',
      maturity_in_days: 70,
      footprint: 12,
      support: false,
      usda_zone: {value : [9, 10, 11]}
    },
    {
      id: '51bdedee-6e4e-4eac-a131-0dc0e112b91e',
      plant_id: '3e6b463b-8e92-4926-b2b1-e842d4c1f1e9',
      name: 'Green Magic',
      description: "Perfect for summer harvests, Green Magic broccoli holds well with improved hybrid bolt resistance. Considered a mid/early variety, it's also good for fall harvests. The large plants are blue/green with uniform, tightly packed heads, excellent flavour, and strong resistance to foliar powdery mildew.",
      sun: 'full',
      frost_tolerance: 'mild',
      maturity_in_days: 60,
      footprint: 12,
      support: false,
      usda_zone: {value : [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]}
    },
    {
      id: 'f08c0353-fceb-47cd-940a-0dec421f954d',
      plant_id: '14b2ac02-0c9c-4e02-85a7-0ac946225d58',
      name: 'Little Gem',
      description: 'Little Gem romaine lettuce seeds produce small, personal size, mini romaine heads that will fit in the palm of your hand. This variety was popularized as a gourmet heirloom treat in England. These little gems grow to about 4" in diameter and are best picked when they are 6" tall.',
      sun: 'partial',
      frost_tolerance: 'mild',
      maturity_in_days: 70,
      footprint: 3,
      support: false,
      usda_zone: {value : [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]}

    },
    {
      id: 'b86d089c-8085-4b44-8294-ee1395702832',
      plant_id: '05cb53c6-15ee-4c42-9e0f-a09468a21725',
      name: 'Spacemaster',
      description: 'Spacemaster cucumber was developed at Cornell University for its highly productive, but very compact vines. Dark green, smooth skinned fruits grow to 15-20cm (6-8") long on individual stems that rarely exceed 90cm (36"). This compact growth makes them a superb choice for container growing or production in smaller gardens. Pick at a smaller size for crunchy pickles, or let them reach full size for slicing.',
      sun: 'full',
      frost_tolerance: 'none',
      maturity_in_days: 58,
      footprint: 12,
      support: true,
      usda_zone: {value : [4, 5, 6, 7, 8, 9, 10, 11, 12]}
    },
    {
      id: '843c5b83-be0a-45a6-bbee-47ae85bb3ff3',
      plant_id: '43d50474-d1f6-4ff9-b2d1-658a2efccba1',
      name: 'Fresca',
      description: "Fresca strawberry seeds are so tiny it's hard to believe that these miniature seeds produce big, mouthwatering traditional strawberries. Start the seeds indoors during the winter and place the seedlings out after the last frost. While they may not produce much fruit the first year, these sprawling plants will eventually yield heavily over a long season. They are considered everbearing, and will flower over and over if plants are kept picked. This strawberry is ideal for containers, raised beds, or hanging baskets. For fruits the first year, give them a really early start in December or January.",
      sun: 'full',
      frost_tolerance: 'none',
      maturity_in_days: 150,
      footprint: 3,
      support: false,
      usda_zone: {value : [4, 5, 6, 7, 8, 9]}
    },
    {
      id: '22122953-c820-400d-98de-087cd57f2436',
      plant_id: '92fe9d1d-1a43-4864-b265-9069079bf2c0',
      name: 'Peaches and Cream',
      description: 'This fantastic mid-season bicolour hybrid produces 22cm (8.5") long cobs, each with 18-20 rows each of white and gold kernels. The kernels actually produce two different flavours in every bite. Peaches and Cream corn seeds produce productive, 2m tall plants and very sweet cobs. Peaches and Cream has earned its popularity for gourmet flavour, sweetness, and tender, fine kernels. We highly recommend it for the home gardener.',
      sun: 'full',
      frost_tolerance: 'none',
      maturity_in_days: 70,
      footprint: 3,
      support: false,
      usda_zone: {value : [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]}

    },
    {
      id: '6cf17966-2442-4058-9ed8-bad38145c745',
      plant_id: '33fc1aaa-a515-4398-96f7-213d48e2feab',
      name: 'Small Sugar',
      description: 'This is the classic (if not original) pie pumpkin with small, round, slightly flattened orange fruits that have very light rib indentations. Each fine-grained, stringless pumpkin averages 20cm (8") tall by 23cm (9") wide. The votes are in, making Small Sugar one of the best of all pumpkins for canning and pies.',
      sun: 'full',
      frost_tolerance: 'none',
      maturity_in_days: 110,
      footprint: 12,
      support: false,
      usda_zone: {value : [3, 4, 5, 6, 7, 8, 9]}
    },
    {
      id: '1dc32cb2-7be8-4152-ae31-16c77ea88add',
      plant_id: 'bb5154f1-ae1f-4545-8437-4b51d3b921fc',
      name: 'French Fingerling',
      description: 'Late season. French Fingerling features the same waxy flesh and petite, oblong shape as Banana Fingerling, but with smooth skin that is dark red, almost the colour of Chieftain. They roast particularly well, and the smooth texture pairs well with other roast vegetables. It is a late season, but quite productive variety.',
      sun: 'full',
      frost_tolerance: 'mild',
      maturity_in_days: 60,
      footprint: 3,
      support: false,
      usda_zone: {value : [3, 4, 5, 6, 7, 8, 9, 10]}
    },
    {
      id: '0668a8f9-f6ce-40b1-afbd-f814ba545710',
      plant_id: 'cc45e787-248b-45ac-90aa-b7540fc5657e',
      name: 'Kentucky Blue',
      description: 'This AAS Winner combines the great flavour of Kentucky Wonder with the cool season hardiness of Blue Lake. Its long, round pods are dark-green and straight, and the plants bear over a long season. The plants grow to 2.5m (8’) and the pods are best at 15-18cm (6-7”).',
      sun: 'full',
      frost_tolerance: 'mild',
      maturity_in_days: 70,
      footprint: 3,
      support: true,
      usda_zone: {value : [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]}
    },
    {
      id: 'f455f4d4-fa57-4c70-9ff6-f9b2ac6a3225',
      plant_id: 'b26b6629-4eb6-4047-8773-1c7cfe6d9ccc',
      name: 'Calibra',
      description: 'Mild yellow globe-shaped storage onions that will reach 15cm (6") in diameter by the end of the season. Sow Calibra storage onion seeds indoors in the spring to produce onions that will store for up to four months. This sweet Spanish type is a long day onion for northern growers. It has a hard body, with well developed storage skins, a round shape and slight shoulders.',
      sun: 'full',
      frost_tolerance: 'mild',
      maturity_in_days: 100,
      footprint: 3,
      support: false,
      usda_zone: {value : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]}
    },
    {
      id: 'e20bb2e8-bebd-4c2a-8ec4-df00fb0b1d7e',
      plant_id: 'a68fe70a-fdd7-4e9c-9572-28db9787159e',
      name: 'Russian Red',
      description: 'Russian Red garlic has a hot, strong garlic flavour with a warm, sweet aftertaste. This garlic has the ability to withstand soggy winter soils better than others. It produces eight to 10 medium-sized cloves and stores for six to eight months.',
      sun: 'full',
      frost_tolerance: 'hard',
      maturity_in_days: 100,
      footprint: 2,
      support: false,
      usda_zone: {value : [3, 4, 5, 6, 7, 8, 9, 10]}
    }
  ]

// generate new random UUIDs for seed by running the file with node
let cultivarDataIdGeneration = () => {
    return [
      {
        id: crypto.randomUUID(),
        plant_id: "0738a646-6aa8-4d5e-b5bd-3c2f6c9a4d56",
        name: 'Cherokee Purple',
        description: 'The Cherokee Purple Heirloom Tomato is a purple coloured variety, cultivated by a Native American Cherokee tribe. The plants are highly productive, producing loads of 12 ounce beefsteak tomatoes with deep red interiors. Its complex sweet flavours make it one of the best tasting heirlooms.',
        sun: 'full',
        frost_tolerance: 'none',
        maturity_in_days: 80,
        footprint: 12,
        support: true,
      },
      {
        id: crypto.randomUUID(),
        plant_id: "ab152a53-8a17-45e2-a864-e9b985c66683",
        name: 'Sugar Daddy',
        description: 'A very productive, bushy plant that benefits from some support, Sugar Daddy snap pea seeds produce pods that become uniquely stringless, 8cm (3") snap peas. They grow in pairs near the top of the plant for easy picking. This variety has good disease resistance, but not to the enation virus that sometimes spreads in mid-summer.',
        sun: 'full',
        frost_tolerance: 'mild',
        maturity_in_days: 68,
        footprint: 2,
        support: true,
      },
      {
        id: crypto.randomUUID(),
        plant_id: "0bdceca3-fafe-47de-8ac3-f57cfe3bbff9",
        name: 'Bolero',
        description: 'A great variety for home or market. Very sweet and crunchy, it is a good keeper in storage or in the ground. Roots are bright orange, up to 20cm (8") long, and slightly tapered, with the typical blunt Nantes tip. High level of resistance to Alternaria blights and powdery mildew.',
        sun: 'full',
        frost_tolerance: 'mild',
        maturity_in_days: 75,
        footprint: 1,
        support: false,
      },
      {
        id: crypto.randomUUID(),
        plant_id: "1b85555f-aff0-4c1f-8b15-31c17392a546",
        name: 'California Wonder',
        description: 'Few bell pepper varieties can compete with the reliable plants produced by California Wonder pepper seeds. In a greenhouse, open field, or in your backyard vegetable garden, this is the variety to grow if you love big, blocky sweet peppers that mature from green to bright fire engine red. The four-lobed fruits are heavy with perfectly smooth skins, and grow to nearly 13cm (5") long and 10cm (4") wide on plants that can grow to 65cm (28") tall.',
        sun: 'full',
        frost_tolerance: 'none',
        maturity_in_days: 75,
        footprint: 12,
        support: false,
      },
      {
        id: crypto.randomUUID(),
        plant_id: "a4c96db8-35a6-4ff2-8a2d-79dd1977c563",
        name: 'Arapaho',
        description: 'This early-ripening hybrid has all the heat of regular cayenne chiles, but the fruits mature much earlier on stout, 45cm (18") tall plants. The fruits can be as long as 20cm (8"). Great for containers, Arapaho Pepper Seeds are productive and spicy, with a sweet red bell pepper undertone in its flavour. 30,000 - 50,000 SHU',
        sun: 'full',
        frost_tolerance: 'none',
        maturity_in_days: 70,
        footprint: 12,
        support: false,
      },
      {
        id: crypto.randomUUID(),
        plant_id: "3e6b463b-8e92-4926-b2b1-e842d4c1f1e9",
        name: 'Green Magic',
        description: 'Perfect for summer harvests, Green Magic broccoli holds well with improved hybrid bolt resistance. Considered a mid/early variety, it\'s also good for fall harvests. The large plants are blue/green with uniform, tightly packed heads, excellent flavour, and strong resistance to foliar powdery mildew.',
        sun: 'full',
        frost_tolerance: 'mild',
        maturity_in_days: 60,
        footprint: 12,
        support: false,
      },
      {
        id: crypto.randomUUID(),
        plant_id: "14b2ac02-0c9c-4e02-85a7-0ac946225d58",
        name: 'Little Gem',
        description: 'Little Gem romaine lettuce seeds produce small, personal size, mini romaine heads that will fit in the palm of your hand. This variety was popularized as a gourmet heirloom treat in England. These little gems grow to about 4" in diameter and are best picked when they are 6" tall.',
        sun: 'partial',
        frost_tolerance: 'mild',
        maturity_in_days: 70,
        footprint: 3,
        support: false,
      },
      {
        id: crypto.randomUUID(),
        plant_id: "05cb53c6-15ee-4c42-9e0f-a09468a21725",
        name: 'Spacemaster',
        description: 'Spacemaster cucumber was developed at Cornell University for its highly productive, but very compact vines. Dark green, smooth skinned fruits grow to 15-20cm (6-8") long on individual stems that rarely exceed 90cm (36"). This compact growth makes them a superb choice for container growing or production in smaller gardens. Pick at a smaller size for crunchy pickles, or let them reach full size for slicing.',
        sun: 'full',
        frost_tolerance: 'none',
        maturity_in_days: 58,
        footprint: 12,
        support: true,
      },
      {
        id: crypto.randomUUID(),
        plant_id: "43d50474-d1f6-4ff9-b2d1-658a2efccba1",
        name: 'Fresca',
        description: 'Fresca strawberry seeds are so tiny it\'s hard to believe that these miniature seeds produce big, mouthwatering traditional strawberries. Start the seeds indoors during the winter and place the seedlings out after the last frost. While they may not produce much fruit the first year, these sprawling plants will eventually yield heavily over a long season. They are considered everbearing, and will flower over and over if plants are kept picked. This strawberry is ideal for containers, raised beds, or hanging baskets. For fruits the first year, give them a really early start in December or January.',
        sun: 'full',
        frost_tolerance: 'none',
        maturity_in_days: 150,
        footprint: 3,
        support: false,
      },
      {
        id: crypto.randomUUID(),
        plant_id: "92fe9d1d-1a43-4864-b265-9069079bf2c0",
        name: 'Peaches and Cream',
        description: 'This fantastic mid-season bicolour hybrid produces 22cm (8.5") long cobs, each with 18-20 rows each of white and gold kernels. The kernels actually produce two different flavours in every bite. Peaches and Cream corn seeds produce productive, 2m tall plants and very sweet cobs. Peaches and Cream has earned its popularity for gourmet flavour, sweetness, and tender, fine kernels. We highly recommend it for the home gardener.',
        sun: 'full',
        frost_tolerance: 'none',
        maturity_in_days: 70,
        footprint: 3,
        support: false,
      },
      {
        id: crypto.randomUUID(),
        plant_id: "33fc1aaa-a515-4398-96f7-213d48e2feab",
        name: 'Small Sugar',
        description: 'This is the classic (if not original) pie pumpkin with small, round, slightly flattened orange fruits that have very light rib indentations. Each fine-grained, stringless pumpkin averages 20cm (8") tall by 23cm (9") wide. The votes are in, making Small Sugar one of the best of all pumpkins for canning and pies.',
        sun: 'full',
        frost_tolerance: 'none',
        maturity_in_days: 110,
        footprint: 12,
        support: false,
      },
      {
        id: crypto.randomUUID(),
        plant_id: "bb5154f1-ae1f-4545-8437-4b51d3b921fc",
        name: 'French Fingerling',
        description: 'Late season. French Fingerling features the same waxy flesh and petite, oblong shape as Banana Fingerling, but with smooth skin that is dark red, almost the colour of Chieftain. They roast particularly well, and the smooth texture pairs well with other roast vegetables. It is a late season, but quite productive variety.',
        sun: 'full',
        frost_tolerance: 'mild',
        maturity_in_days: 60,
        footprint: 3,
        support: false,
      },
      {
        id: crypto.randomUUID(),
        plant_id: "cc45e787-248b-45ac-90aa-b7540fc5657e",
        name: 'Kentucky Blue',
        description: 'This AAS Winner combines the great flavour of Kentucky Wonder with the cool season hardiness of Blue Lake. Its long, round pods are dark-green and straight, and the plants bear over a long season. The plants grow to 2.5m (8’) and the pods are best at 15-18cm (6-7”).',
        sun: 'full',
        frost_tolerance: 'mild',
        maturity_in_days: 70,
        footprint: 3,
        support: true,
      },
      {
        id: crypto.randomUUID(),
        plant_id: "b26b6629-4eb6-4047-8773-1c7cfe6d9ccc",
        name: 'Calibra',
        description: 'Mild yellow globe-shaped storage onions that will reach 15cm (6") in diameter by the end of the season. Sow Calibra storage onion seeds indoors in the spring to produce onions that will store for up to four months. This sweet Spanish type is a long day onion for northern growers. It has a hard body, with well developed storage skins, a round shape and slight shoulders.',
        sun: 'full',
        frost_tolerance: 'mild',
        maturity_in_days: 100,
        footprint: 3,
        support: false,
      },
      {
        id: crypto.randomUUID(),
        plant_id: "a68fe70a-fdd7-4e9c-9572-28db9787159e",
        name: 'Russian Red',
        description: 'Russian Red garlic has a hot, strong garlic flavour with a warm, sweet aftertaste. This garlic has the ability to withstand soggy winter soils better than others. It produces eight to 10 medium-sized cloves and stores for six to eight months.',
        sun: 'full',
        frost_tolerance: 'hard',
        maturity_in_days: 100,
        footprint: 2,
        support: false,
      },
      
    ];
  };

  console.log(cultivarDataIdGeneration())