module.exports = [
  {
    id: "33e2ecc6-77a7-4c17-813b-7544aa55c480",
    name: "Window Box",
    type: "Planter",
    height: 8,
    width: 6,
    length: 24,
    radius: 0,
    round: false,
  },
  {
    id: "cb72f37d-e0ea-4fd4-9ac3-db5ba46205d1",
    name: "Large Raised Bed",
    type: "Raised Bed",
    height: 18,
    width: 36,
    length: 72,
    radius: 0,
    round: false,
  },
  {
    id: "7008d119-7f02-4ddc-8b98-13752a9986c5",
    name: "Round Raised Bed",
    type: "Raised Bed",
    height: 24,
    width: 0,
    length: 0,
    radius: 9,
    round: true,
  },
  {
    id: "bafa8ab7-670a-4b84-8b53-52f92a960470",
    name: "5Gal pot",
    type: "Planter",
    height: 18,
    width: 0,
    length: 0,
    radius: 6,
    round: true,
  },
  {
    id: "ec89aa47-ea30-40a1-b402-20509db229d5",
    name: "Square-Foot bed",
    type: "In Ground",
    height: 0,
    width: 48,
    length: 48,
    radius: 0,
    round: false,
  },
  {
    id: "ed7b89f7-0096-434a-9f12-3925e2cbcab1",
    name: "Small Square-Foot bed",
    type: "In Ground",
    height: 0,
    width: 24,
    length: 48,
    radius: 0,
    round: false,
  },
];

// generate new random UUIDs for seed by running the file with node
let planterDataIdGeneration = () => {
  return [
    {
      id: crypto.randomUUID(),
      name: "Window Box",
      type: "Planter",
      height: 8,
      width: 6,
      length: 24,
      radius: 0,
      round: false,
    },
    {
      id: crypto.randomUUID(),
      name: "Large Raised Bed",
      type: "Raised Bed",
      height: 18,
      width: 36,
      length: 72,
      radius: 0,
      round: false,
    },
    {
      id: crypto.randomUUID(),
      name: "Round Raised Bed",
      type: "Raised Bed",
      height: 24,
      width: 0,
      length: 0,
      radius: 9,
      round: true,
    },
    {
      id: crypto.randomUUID(),
      name: "5Gal pot",
      type: "Planter",
      height: 18,
      width: 0,
      length: 0,
      radius: 6,
      round: true,
    },
    {
      id: crypto.randomUUID(),
      name: "Square-Foot bed",
      type: "In Ground",
      height: 0,
      width: 48,
      length: 48,
      radius: 0,
      round: false,
    },
    {
      id: crypto.randomUUID(),
      name: "Small Square-Foot bed",
      type: "In Ground",
      height: 0,
      width: 24,
      length: 48,
      radius: 0,
      round: false,
    },
  ];
};

console.log(planterDataIdGeneration());
